### ISSUE TITLE
Faltam links para API?

### ISSUE THREAD

**Issue by rlafuente** [meuparlamento/react-native-app#1]
Olá,

O ficheiro [config](https://github.com/meuparlamento/react-native-app/blob/master/config.json) tem placeholders para os endereços da API, sem os quais é impossível correr a aplicação como devido.

É possível colocar esses URLs no código fonte?

**Comment by arianpasquali** [comment]
Olá @rlafuente 
Essa é uma questão importante :)

Poderíamos publicar as urls no config, mas infelizmente essa não é a melhor alternativa uma vez que pode acarretar custos adicionais na nossa conta AWS. 

Por essa razão estamos preparando o repositório do projeto [backend](https://github.com/meuparlamento/meuparlamento-backend-api) para permitir que qualquer pessoa possa executar a sua própria instância da aplicação mobile e do servidor. 

Vamos comunicar em breve assim que o repositório estiver no ar
Stay tuned :)

**Comment by arianpasquali** [comment]
Olá @rlafuente 
O código do servidor já está disponível em https://github.com/meuparlamento/meuparlamento-backend-api/

Veja se consegues reproduzir. Qualquer dúvida estamos aqui.

**Comment by gsilvapt** [comment]
Uma vez que estão a usar Docker, fica a sugestão de as imagens fazerem build com variaveis de ambiente que, por sua vez, seriam introduzidos por cada user.
